In [10]:
import pandas as pd
import numpy as np

In [11]:
Arr=np.array([[j for j in range(i,i+4)] for i in range(1,12,4)])
print(Arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [12]:
y=np.array([i for i in range(1,7)])
print(y)

[1 2 3 4 5 6]


In [13]:
print(str(Arr[1,3])+'\n'+str(Arr[2,2])+'\n'+str(Arr[1,2]))

8
11
7


In [14]:
print(y[:3])
print(y[-3:])

[1 2 3]
[4 5 6]


In [15]:
print('2D Matrix:')
print('No. of elements:',len(Arr)*len(Arr[0]))
print('Dimensions: (Rows,Colums):',np.shape(Arr))

2D Matrix:
No. of elements: 12
Dimensions: (Rows,Colums): (3, 4)


In [16]:
print(np.info(Arr))

class:  ndarray
shape:  (3, 4)
strides:  (16, 4)
itemsize:  4
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x1fb22875eb0
byteorder:  little
byteswap:  False
type: int32
None


In [29]:
print('Y:')
print('No. of elements:',len(y))
print('___________________')
print('Shape:',y.shape)
print('Size:',y.size)

Y:
No. of elements: 6
___________________
Shape: (6,)
Size: 6


In [31]:
X=Arr+10
print(X)

[[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]


In [33]:
print('Arr:')
print(np.max(Arr))
print(np.min(Arr))
print('Y:')
print(np.max(y))
print(np.min(y))

Arr:
12
1
Y:
6
1


In [35]:
print(np.average(Arr))
print(np.std(Arr))
print(np.var(Arr))

6.5
3.452052529534663
11.916666666666666


In [37]:
print(np.average(y))
print(np.std(y))
print(np.var(y))

3.5
1.707825127659933
2.9166666666666665


In [39]:
print(Arr.reshape(2,6))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [41]:
print(np.transpose(Arr))
print(np.transpose(y))

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
[1 2 3 4 5 6]


In [43]:
print(Arr.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [45]:
P=np.array([[1,3,6],[1,4,5],[2,2,7]])
# a. Find and display the rank of P
rank = np.linalg.matrix_rank(P)

# b. Find and display the determinant of P
determinant = np.linalg.det(P)

# c. Find and display the diagonal of P
diagonal = np.diagonal(P)

# d. Find and display the trace of P
trace = np.trace(P)

# e. Find the eigenvalues and eigenvectors of P
eigenvalues, eigenvectors = np.linalg.eig(P)

# Display the results
print(f"Rank of P: {rank}")
print(f"Determinant of P: {determinant}")
print(f"Diagonal of P: {diagonal}")
print(f"Trace of P: {trace}")
print(f"Eigenvalues of P: {eigenvalues}")
print("Eigenvectors of P:")
print(eigenvectors)


Rank of P: 3
Determinant of P: -8.999999999999998
Diagonal of P: [1 4 7]
Trace of P: 12
Eigenvalues of P: [10.59900683 -0.45701438  1.85800755]
Eigenvectors of P:
[[-0.55902488 -0.95323847 -0.18562955]
 [-0.55289125 -0.10432388 -0.88924337]
 [-0.61790165  0.2836423   0.41807643]]


In [47]:
z=np.array([2,3,6,2,5,2])
print('Dot Product (y.z):',(y*z))

Dot Product (y.z): [ 2  6 18  8 25 12]


In [49]:
Q=np.array([[4,6,7],[5,5,2],[3,4,6]])
print(P+Q)
print(P-Q)
print(P*Q)
print(np.linalg.inv(P))
print(np.linalg.inv(Q))

[[ 5  9 13]
 [ 6  9  7]
 [ 5  6 13]]
[[-3 -3 -1]
 [-4 -1  3]
 [-1 -2  1]]
[[ 4 18 42]
 [ 5 20 10]
 [ 6  8 42]]
[[-2.          1.          1.        ]
 [-0.33333333  0.55555556 -0.11111111]
 [ 0.66666667 -0.44444444 -0.11111111]]
[[-1.04761905  0.38095238  1.0952381 ]
 [ 1.14285714 -0.14285714 -1.28571429]
 [-0.23809524 -0.0952381   0.47619048]]


In [51]:
uniform_random_numbers = np.random.uniform(low=0.0, high=1.0, size=10)
gaussian_random_numbers = np.random.normal(loc=0.0, scale=1.0, size=10)
logistic_random_numbers = np.random.logistic(loc=0.0, scale=1.0, size=10)
print("Uniform Distribution (10 numbers):")
print(uniform_random_numbers)

print("\nGaussian Distribution (10 numbers):")
print(gaussian_random_numbers)

print("\nLogistic Distribution (10 numbers):")
print(logistic_random_numbers)

Uniform Distribution (10 numbers):
[0.12520752 0.10115654 0.2597649  0.62786621 0.09649919 0.84400723
 0.88023619 0.22105005 0.57066202 0.45357167]

Gaussian Distribution (10 numbers):
[ 0.52945321 -1.07917448  0.89761643 -0.15083407 -0.43119684  1.40473667
  0.61821253 -0.34034696 -0.35834923  0.76171383]

Logistic Distribution (10 numbers):
[ 0.1642523  -1.044314   -2.93997439  0.16990402  0.63131274  0.87868103
  0.66093065 -2.36789384 -0.44988469 -1.81477738]
